/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  Doc_sidebar: [{type: 'autogenerated', dirName: '.'}],
/*
  aaa_sidebar: [
    {
      type: 'doc',
      label: '项目介绍',
      id: 'intro',
    },
    {
      type: 'category',
      label: '快速开始',
      items: ['quick-start'],
    },
    {
      type: 'category',
      label: '主题配置',
      items: ['configuration-guide'],
    },
    {
      type: 'category',
      label: '进阶配置',
      items: ['advanced'],
    },
  ],
*/
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
